<?php
namespace Wei\Base\Tests\DB;

use Wei\Base\DB\PdoQuery;
use Wei\Base\Tests\WeiTestCase;

class PdoQueryTest extends WeiTestCase
{
    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub

    }



    /**
     * 通用基镜
     */
    public static function setFixture()
    {

    }
    /**
     * 测试查询字段[select]
     */
    public function testSelect()
    {
        //字符串字段查询
        $pdoQuery = new PdoQuery();
        $pdoQuery->select('id,name,age');
        list($str, $params) = $pdoQuery->getSelect();
        $this->assertEquals('?,?,?', $str);
        $this->assertEquals(['id', 'name', 'age'], $params);

        //空字符串字段查询
        $pdoQuery = new PdoQuery();
        $pdoQuery->select('');
        list($str, $params) = $pdoQuery->getSelect();
        $this->assertEquals('', $str);
        $this->assertEquals([], $params);


        //数组字段查询
        $pdoQuery = new PdoQuery();
        $pdoQuery->select(['id', 'name', 'age']);
        list($str, $params) = $pdoQuery->getSelect();
        $this->assertEquals('?,?,?', $str);
        $this->assertEquals(['id', 'name', 'age'], $params);

        //数组空字段查询
        $pdoQuery = new PdoQuery();
        $pdoQuery->select([]);
        list($str, $params) = $pdoQuery->getSelect();
        $this->assertEquals('', $str);
        $this->assertEquals([], $params);



    }

    /**
     * 测试查询字段[select]
     */
    public function testSelectAddSelect()
    {
        //数组查询再追加数组查询再追加字符
        $pdoQuery = new PdoQuery();
        $pdoQuery->select(['id','age']);
        $pdoQuery->addSelect(['uid','name']);
        $pdoQuery->addSelect('created');
        $pdoQuery->addSelect('');
        $pdoQuery->addSelect([]);
        list($str, $params) = $pdoQuery->getSelect();
        $this->assertEquals('?,?,?,?,?', $str);
        $this->assertEquals(['id', 'age', 'uid', 'name', 'created'], $params);

    }

    /**
     * 测试[from]
     */
    public function testFrom()
    {
        $pdoQuery = new PdoQuery();
        $pdoQuery->from('wei_test');
        $this->assertEquals('wei_test', $pdoQuery->getFrom());
    }

    /**
     * 测试空表名
     * @expectedException \Wei\Base\Exception\QueryException
     */
    public function testFormThrowException()
    {
        $pdoQuery = new PdoQuery();
        $pdoQuery->getFrom();
    }

    /**
     * 测试where条件
     */
    public function testWhere()
    {
        //字符串where
        $pdoQuery = new PdoQuery();
        $pdoQuery->where('id=1 and name=2');
        list($str, $params) = $pdoQuery->getWhere();
        $this->assertEquals('?', $str);
        $this->assertEquals(['id=1 and name=2'], $params);

        //数组where
        $pdoQuery = new PdoQuery();
        $pdoQuery->where(['id' => 1]);
        list($str, $params) = $pdoQuery->getWhere();
        $this->assertEquals('id = ?', $str);
        $this->assertEquals([1], $params);

        //数组where
        $pdoQuery = new PdoQuery();
        $pdoQuery->where(['id' => 1, 'name' => 'xiao']);
        list($str, $params) = $pdoQuery->getWhere();
        $this->assertEquals('id = ? and name = ?', $str);
        $this->assertEquals([1, 'xiao'], $params);

        //数组like where
        $where = [
            'name' => [
                'op' => 'like',
                'test%'
            ]
        ];
        $pdoQuery = new PdoQuery();
        $pdoQuery->where($where);
        list($str, $params) = $pdoQuery->getWhere();
        $this->assertEquals('name like ?', $str);
        $this->assertEquals(['test%'], $params);

        //数组常用where
        $where = [
            'id' => 3,
            'name' => [
                'on' => 'and',
                'op' => 'in',
                'rawValue' => "('test1','test2')",
            ],
            'age' => [
                'on' => 'or',
                'op' => '>=',
                '5',
            ],
            '`age`' => [
                'on' => 'or',
                'op' => '<=',
                'rawValue' => 10,
            ],
            'tid' => [
                'on' => 'OR',
                'op' => '<=',
                'rawValue' => 11,
            ]
        ];
        $pdoQuery = new PdoQuery();
        $pdoQuery->where($where);
        list($str, $params) = $pdoQuery->getWhere();
        $this->assertEquals('id = ? and name in ? or age >= ? or `age` <= ? or tid <= ?', $str);
        $this->assertEquals([3, "('test1','test2')", "5", 10, 11], $params);

    }

    /**
     * 测试where in
     */
    public function testWhereIn()
    {
        $pdoQuery = new PdoQuery();
        $pdoQuery->where('id=1 and name=2');
        $pdoQuery->andWhere([
            'age' => [
                'op' => 'in',
                [20,30,40,50,100]
            ]
        ]);
        list($str, $params) = $pdoQuery->getWhere();
        $this->assertEquals('? and age in (?,?,?,?,?)', $str);
        $this->assertEquals(["id=1 and name=2", 20, 30, 40, 50 ,100], $params);
    }

    /**
     * 测试分组查询[group by ]
     */
    public function testGroupBy()
    {
        $str = '';
        $params = '';
        print_r($str);
        print_r($params);
    }

    /**
     * 测试排序[order by]
     */
    public function testOrderBy()
    {

    }

    /**
     * 测试offset
     */
    public function testOff()
    {

    }

    /**
     * 返回多少条数据
     */
    public function testLimit()
    {

    }

    /**
     * 测试连接
     */
    public function testJoin()
    {

    }

    /**
     * 内联查询
     */
    public function testInner()
    {

    }

    /**
     * 左连查询
     */
    public function testLeftJoin()
    {

    }

    /**
     * 右连查询
     */
    public function testRightJoin()
    {

    }

    /**
     * 设置删除基镜
     */
    public static function setFixtureForTestDelete()
    {

    }

    /**
     * 测试插入多行数据
     */
    public function testInsertAll()
    {

    }
    /**
     * 测试查询单行数据
     */
    public function testOne()
    {

    }

    /**
     * 测试查询多行记录
     *
     * @depends testOne
     */
    public function testAll()
    {

    }

    /**
     * 测试删除
     * @depends testOne
     */
    public function testDelete()
    {

    }
    /**
     * 测试最小查询
     * @depends testOne
     */
    public function testMin()
    {
    }

    /**
     * 测试最大值
     * @depends testOne
     */
    public function testMax()
    {

    }

    /**
     * 测试总和
     *
     * @depends testOne
     */
    public function testSum()
    {

    }

    /**
     * 测试平均值
     * @depends testOne
     */
    public function testAverage()
    {

    }

    /**
     * 测试统计
     * @depends testAverage
     */
    public function testCount()
    {


    }

    /**
     * 更改数据
     */
    public function testUpdate()
    {

    }

    /**
     * 批量更新
     * @depends testOne
     */
    public function testUpdataAll()
    {

    }
}